title: Jineui Park 2021 Resume
author: jineuip
email: jineuip
description: > # this means to ignore newlines until "baseurl:"
  new 2021 Resume

# social links
twitter_username: n/a # DO NOT include the @ character, or else the build will fail!
github_username:  jineuip # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
